# catppuccin latte palette
set -g @thm_bg          "#eff1f5"
set -g @thm_red         "#d20f39"
set -g @thm_maroon      "#e64553"
set -g @thm_peach       "#fe640b"
set -g @thm_yellow      "#df8e1d"
set -g @thm_green       "#40a02b"
set -g @thm_blue        "#1e66f5"
set -g @thm_rosewater   "#dc8a78"
set -g @thm_surface_0   "#ccd0da"
set -g @thm_overlay_0   "#9ca0b0"
